name             'tomcat'
maintainer       'Gil Gyeong-Min'
maintainer_email 'rushcut@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures tomcat'
long_description 'Installs/Configures tomcat'
version          '0.1.0'

depends 'apt'
depends 'java'
depends 'nginx'
